<?php
// Commerce color definitions
$info = array(
  'fields' => array(
    'base'                   => t('Background'),
    'link'                   => t('Links'),
    'text'                   => t('Text'),
    'titles'                 => t('Titles'),
    'borders'                => t('Borders'),
    'sticky'                 => t('Sticky article'),
    'site_name'              => t('Site name'),
    'site_slogan'            => t('Site slogan'),
    'top'                    => t('Header top'),
    'bottom'                 => t('Header bottom'),

    'main_menu'              => t('Main menu'),
    'main_menu_links'        => t('Main menu links'),

    'button_cart_top'        => t('Add to cart top'),
    'button_cart_bottom'     => t('Add to cart bottom'),
    'button_cart_text'       => t('Add to cart text'),

    'button_top'             => t('Button top'),
    'button_bottom'          => t('Button bottom'),
    'button_text'            => t('Button text'),

    'secondary'              => t('Secondary panel background'),
    'secondary_text'         => t('Secondary panel text'),
    'secondary_links'        => t('Secondary panel links'),

    'bottom_panels'          => t('Bottom panels background'),
    'bottom_panels_text'     => t('Bottom panels text'),
    'bottom_panels_links'    => t('Bottom panels links'),

    'footer_panels'          => t('Footer panels background'),
    'footer_panels_text'     => t('Footer panels text'),
    'footer_panels_links'    => t('Footer panels links'),

    'footer'                 => t('Page Footer'),
  ),
  'schemes' => array(
    'default' => array(
      'title' => t('Commerce Minimal Cool (Default)'),
      'colors' => array(
        'base'                   => '#f5f5f5',
        'link'                   => '#007fff',
        'text'                   => '#666666',
        'titles'                 => '#2c2c2c',
        'borders'                => '#d5d5d5',
        'sticky'                 => '#f9f9f9',
        'site_name'              => '#111111',
        'site_slogan'            => '#333333',
        'top'                    => '#efefef',
        'bottom'                 => '#e7e7e7',

        'main_menu'              => '#212121',
        'main_menu_links'        => '#fcfcfc',

        'button_cart_top'        => '#007100',
        'button_cart_bottom'     => '#588e51',
        'button_cart_text'       => '#ffffff',

        'button_top'             => '#e7e7e7',
        'button_bottom'          => '#efefef',
        'button_text'            => '#333333',

        'secondary'              => '#dddddd',
        'secondary_text'         => '#414141',
        'secondary_links'        => '#101010',

        'bottom_panels'          => '#e7e7e7',
        'bottom_panels_text'     => '#555555',
        'bottom_panels_links'    => '#f0f0f0',

        'footer_panels'          => '#202020',
        'footer_panels_text'     => '#ababab',
        'footer_panels_links'    => '#dedede',

        'footer'                 => '#e2e2e2',
      ),
    ),
    'scheme_tiger_lily' => array(
      'title' => t('Tiger Lily'),
      'colors' => array(

        'base'                   => '#ffffff',
        'link'                   => '#ee6630',
        'text'                   => '#555555',
        'titles'                 => '#2c2c2c',
        'borders'                => '#e0e3d6',
        'sticky'                 => '#f9f9f9',
        'site_name'              => '#111111',
        'site_slogan'            => '#333333',
        'top'                    => '#d6e99a',
        'bottom'                 => '#d6e99a',

        'main_menu'              => '#51611e',
        'main_menu_links'        => '#fffff0',

        'button_cart_top'        => '#007100',
        'button_cart_bottom'     => '#588e51',
        'button_cart_text'       => '#ffffff',

        'button_top'             => '#e7e7e7',
        'button_bottom'          => '#efefef',
        'button_text'            => '#333333',

        'secondary'              => '#afc46a',
        'secondary_text'         => '#414141',
        'secondary_links'        => '#101010',

        'bottom_panels'          => '#e7e7e7',
        'bottom_panels_text'     => '#555555',
        'bottom_panels_links'    => '#f0f0f0',

        'footer_panels'          => '#101404',
        'footer_panels_text'     => '#fffff0',
        'footer_panels_links'    => '#fffff0',

        'footer'                 => '#ffffff',
      ),
    ),
  ),
  'css' => array(
    'color/colors.css',
  ),
  'copy' => array(
    'logo.png',
  ),
  'gradients' => array(
    array(
      'dimension' => array(0, 0, 0, 0),
      'direction' => 'vertical',
      'colors' => array('top', 'bottom'),
    ),
  ),
  'fill' => array(),
  'slices' => array(),
  'blend_target' => '#ffffff',
  'preview_image' => 'color/color-preview.png',
  'preview_css' => 'color/preview.css',
  'base_image' => 'color/base.png',
);
